spring : 
      datasource:
            url: jdbc:mysql://localhost:3306/subscription_management_system
            username: root
            password: admin
            driver-class-name: com.mysql.cj.jdbc.Driver
      jpa: 
            show-sql: true
            format-sql: true
            hibernate: 
                  ddl-auto: create
      application: 
            name: Subscription_Management_Service
            
server: 
      port: 80